# Change these first
owner: janeapp # Your GitHub organization or username, where this repository lives
repo: clinic-sites-uptime # The name of this repository

sites:
  - name: ClinicSites Production
    url: https://clinicsites.co
  - name: ClinicSites Previews
    url: https://template1.clinicsites.co
assignees:
  - James-Pike-Jane

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: clinic-sites-uptime
  logoUrl: https://raw.githubusercontent.com/$OWNER/$REPO/assets/clinicsites.svg
  name: ClinicSites
  introTitle: "**ClinicSites** the best platform for building your clinic's website."
  introMessage: "This is the ClinicSites status page, powered by Upptime."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
