# See https://upptime.js.org/docs/configuration

owner: janeapp 
repo: clinic-sites-uptime

sites:
  - name: ClinicSites.co
    url: https://clinicsites.co
  - name: Clinic Sites Site Preview
    url: https://template1.clinicsites.co
    faviconSvg: https://icons.duckduckgo.com/ip3/clinicsites.co.ico
  - name: Clinic Sites Live Domain
    url: $CLINIC_SITES_LIVE_DOMAIN
    favicon: https://icons.duckduckgo.com/ip3/clinicsites.co.ico
assignees:
  - James-Pike-Jane
  - brycemevans-jane
  - phil-janeapp

status-website:
  cname: status.clinicsites.co
  logoUrl: https://raw.githubusercontent.com/janeapp/clinic-sites-uptime/master/assets/clinicsites.svg
  faviconSvg: https://raw.githubusercontent.com/janeapp/clinic-sites-uptime/master/assets/clinicsites.svg
  name: "Clinic Sites"
  introTitle: "**Clinic Sites** the best platform for building your clinic's website."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# These are the default values - Included for reference
# They can be changed here if needed
# Keep in mind GitHub Actions cannot run faster than every 5 minutes
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"


