# See https://upptime.js.org/docs/configuration

owner: janeapp 
repo: clinic-sites-uptime

sites:
  - name: ClinicSites Production
    url: https://clinicsites.co
  - name: ClinicSites Previews
    url: https://template1.clinicsites.co
    faviconSvg: https://raw.githubusercontent.com/janeapp/clinic-sites-uptime/master/assets/clinicsites.svg
  - name: ClinicSites Live Domain
    url: $CLINIC_SITES_LIVE_DOMAIN
    faviconSvg: https://raw.githubusercontent.com/janeapp/clinic-sites-uptime/master/assets/clinicsites.svg
assignees:
  - James-Pike-Jane
  - brycemevans-jane
  - phil-janeapp

status-website:
  cname: status.clinicsites.co
  logoUrl: https://raw.githubusercontent.com/janeapp/clinic-sites-uptime/master/assets/clinicsites.svg
  faviconSvg: https://raw.githubusercontent.com/janeapp/clinic-sites-uptime/master/assets/clinicsites.svg
  name: ClinicSites
  introTitle: "**ClinicSites** the best platform for building your clinic's website."
  introMessage: "This is the ClinicSites status page, powered by Upptime."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# These are the default values - Included for reference
# Keep in mind GitHub Actions cannot run faster than every 5 minutes
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"


